---
name: "Feature Request"
description: "Suggest a new feature for the Paynow Raycast extension."
title: "[Feature Request]: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A short summary of the feature you are requesting.
      placeholder: e.g. Add support for X
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
      placeholder: Explain the use case and why it is important.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this feature implemented?
      placeholder: Describe your ideal solution or any ideas you have.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: List any alternatives you've thought about.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: Any other details...
    validations:
      required: false
